name: Update Profile README

on:
  push:
    # Run on main branch pushes or PRs
    branches: [main]
  pull_request:
    branches: [main]
  # Allow to manually trigger the workflow
  workflow_dispatch:
  schedule:
    # Rebuild every day at 16:30 PM UTC
    - cron: "30 16 * * *"

jobs:
  build:
    # What OS to use
    runs-on: ubuntu-latest
    # Allow commits to the repository
    permissions:
      id-token: write
      contents: write
      pages: write

    # What steps to run
    steps:
      - name: Clone repository
        # Git clone the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: "0" # Fetch all history for git

      - name: Setup Deno environment
        # Downloads deno and caches it
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          # Latest Deno 2.x version
          deno-version: v2.x

      - name: Build site
        # Run the build script from deno.json
        env:
          API_KEY_01: ${{ secrets.PRODBKEY }}
        run: deno task build

      - name: Commit changes
        # Commit the changes to the repository
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: Apply changes during gh actions build
          status_options: "--untracked-files=no"

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: "_site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
